services:
  - type: web
    name: csastudentmanagement
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    releaseCommand: python scripts/startup.py --migrate-only
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /home
